[package]
name = "dindex"
version = "0.1.0"
authors = ["Jeffrey McAteer <jeffrey.p.mcateer@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.9.3"
dirs = "2.0.1"
victorem = "0.8.2"

rand = "0.6.5"
regex = "1"

serde = { version = "1.0.92", features = ["derive"] }
serde_cbor = "0.9"
serde_json = "1.0"

[lib]
name = "dindex"
path = "src/lib.rs"

[[bin]]
name = "dindex-server"
path = "src/server_main.rs"

[[bin]]
name = "dindex-client"
path = "src/client_main.rs"
