[package]
name = "dindex"
version = "0.1.0"
authors = ["Jeffrey McAteer <jeffrey.p.mcateer@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.9.3"
dirs = "2.0.1"

[lib]
name = "dindex"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/server_main.rs"

[[bin]]
name = "client"
path = "src/client_main.rs"
