listen_ip = "0.0.0.0"
# 0x1de0 in hex - wanted to say "index"
listen_port = 7648

# To make abusing the system for Amplification attacks
# impossible, the server will never reply with more bytes than
# what the client gave it. To receive a useful amount of results,
# clients should add a special ephemeral padding field in their query.
query_padding_bytes = 4096

anon_max_bytes_sent_per_ip_per_sec = 16384

trusted_ip_sources = [
  "127.0.0.1"
]

# This is best for small setups with <1000 trusted users. (though you not use /tmp/ to store meaningful data in)
authorized_keys_file = "/tmp/dindex_authorized_keys"

# This has not been implemented but is planned;
# we will use http://diesel.rs/guides/getting-started/ to connect to a large
# number of database backends. The URL points to the table or view to be queried,
# and the query is the query to be run. The "{}" within the query string is replaced by the public key of the user authenticating.
authorized_keys_sql_backend_url = "postgres://username:password@localhost/diesel_demo"
authorized_keys_sql_query = "SELECT * FROM auth_keys_table WHERE key_string  = {}"

identity_private_key_file = "/dev/null"
identity_public_key_file = "/dev/null"

cache_dir = "/tmp/dindex_cache/"
cache_max_bytes = 4294967296

# Each of these is a single entry in the
# list of servers which will be queried if
# we do not know enough to answer a given query
[[upstream_resolvers]]
host = "dindex.jmcateer.pw"
# Optional; we default to 7648
port = 7648
# Optional; we default to dropping connections to this server after 600ms latency.
max_latency_ms = 600




